### ISSUE TITLE
Doesn't seem to work on raspberry pi

### ISSUE THREAD

**Issue by sdaitzman** [billroy/serial-web-terminal#1]
I tried to run it on a raspberry pi; here are a couple attempts:

```
samuel@samrmbp in ~/: ➤ ssh pi@192.168.1.158
pi@192.168.1.158's password:
Linux raspberrypi 3.10.36+ #664 PREEMPT Mon Apr 7 14:01:14 BST 2014 armv6l

The programs included with the Debian GNU/Linux system are free software;
the exact distribution terms for each program are described in the
individual files in /usr/share/doc/*/copyright.

Debian GNU/Linux comes with ABSOLUTELY NO WARRANTY, to the extent
permitted by applicable law.
Last login: Thu May 29 12:49:18 2014 from samrmbp.local
Welcome to fish, the friendly interactive shell
Type help for instructions on how to use fish
pi@raspberrypi ~> ls /dev/ttyusb&
ls: cannot access /dev/ttyusb: No such file or directory
Job 1, “ls /dev/ttyusb&” has ended
pi@raspberrypi ~> ls /dev/ttyusb*
fish: Warning: No match for wildcard “/dev/ttyusb*”. The command will not be
executed.
ls /dev/ttyusb*
   ^
pi@raspberrypi ~> ls /dev/tty&
/dev/tty
Job 1, “ls /dev/tty&” has ended
pi@raspberrypi ~> ls /dev/tty*
/dev/tty    /dev/tty19  /dev/tty3   /dev/tty40  /dev/tty51  /dev/tty62
/dev/tty0   /dev/tty2   /dev/tty30  /dev/tty41  /dev/tty52  /dev/tty63
/dev/tty1   /dev/tty20  /dev/tty31  /dev/tty42  /dev/tty53  /dev/tty7
/dev/tty10  /dev/tty21  /dev/tty32  /dev/tty43  /dev/tty54  /dev/tty8
/dev/tty11  /dev/tty22  /dev/tty33  /dev/tty44  /dev/tty55  /dev/tty9
/dev/tty12  /dev/tty23  /dev/tty34  /dev/tty45  /dev/tty56  /dev/ttyAMA0
/dev/tty13  /dev/tty24  /dev/tty35  /dev/tty46  /dev/tty57  /dev/ttyprintk
/dev/tty14  /dev/tty25  /dev/tty36  /dev/tty47  /dev/tty58
/dev/tty15  /dev/tty26  /dev/tty37  /dev/tty48  /dev/tty59
/dev/tty16  /dev/tty27  /dev/tty38  /dev/tty49  /dev/tty6
/dev/tty17  /dev/tty28  /dev/tty39  /dev/tty5   /dev/tty60
/dev/tty18  /dev/tty29  /dev/tty4   /dev/tty50  /dev/tty61
pi@raspberrypi ~> ls /dev/tty*
/dev/tty    /dev/tty19  /dev/tty3   /dev/tty40  /dev/tty51  /dev/tty62
/dev/tty0   /dev/tty2   /dev/tty30  /dev/tty41  /dev/tty52  /dev/tty63
/dev/tty1   /dev/tty20  /dev/tty31  /dev/tty42  /dev/tty53  /dev/tty7
/dev/tty10  /dev/tty21  /dev/tty32  /dev/tty43  /dev/tty54  /dev/tty8
/dev/tty11  /dev/tty22  /dev/tty33  /dev/tty44  /dev/tty55  /dev/tty9
/dev/tty12  /dev/tty23  /dev/tty34  /dev/tty45  /dev/tty56  /dev/ttyAMA0
/dev/tty13  /dev/tty24  /dev/tty35  /dev/tty46  /dev/tty57  /dev/ttyprintk
/dev/tty14  /dev/tty25  /dev/tty36  /dev/tty47  /dev/tty58
/dev/tty15  /dev/tty26  /dev/tty37  /dev/tty48  /dev/tty59
/dev/tty16  /dev/tty27  /dev/tty38  /dev/tty49  /dev/tty6
/dev/tty17  /dev/tty28  /dev/tty39  /dev/tty5   /dev/tty60
/dev/tty18  /dev/tty29  /dev/tty4   /dev/tty50  /dev/tty61
pi@raspberrypi ~> ls /dev/tty*
/dev/tty    /dev/tty19  /dev/tty3   /dev/tty40  /dev/tty51  /dev/tty62
/dev/tty0   /dev/tty2   /dev/tty30  /dev/tty41  /dev/tty52  /dev/tty63
/dev/tty1   /dev/tty20  /dev/tty31  /dev/tty42  /dev/tty53  /dev/tty7
/dev/tty10  /dev/tty21  /dev/tty32  /dev/tty43  /dev/tty54  /dev/tty8
/dev/tty11  /dev/tty22  /dev/tty33  /dev/tty44  /dev/tty55  /dev/tty9
/dev/tty12  /dev/tty23  /dev/tty34  /dev/tty45  /dev/tty56  /dev/ttyACM0
/dev/tty13  /dev/tty24  /dev/tty35  /dev/tty46  /dev/tty57  /dev/ttyAMA0
/dev/tty14  /dev/tty25  /dev/tty36  /dev/tty47  /dev/tty58  /dev/ttyprintk
/dev/tty15  /dev/tty26  /dev/tty37  /dev/tty48  /dev/tty59
/dev/tty16  /dev/tty27  /dev/tty38  /dev/tty49  /dev/tty6
/dev/tty17  /dev/tty28  /dev/tty39  /dev/tty5   /dev/tty60
/dev/tty18  /dev/tty29  /dev/tty4   /dev/tty50  /dev/tty61
pi@raspberrypi ~> ls /dev/tty*
/dev/tty    /dev/tty19  /dev/tty3   /dev/tty40  /dev/tty51  /dev/tty62
/dev/tty0   /dev/tty2   /dev/tty30  /dev/tty41  /dev/tty52  /dev/tty63
/dev/tty1   /dev/tty20  /dev/tty31  /dev/tty42  /dev/tty53  /dev/tty7
/dev/tty10  /dev/tty21  /dev/tty32  /dev/tty43  /dev/tty54  /dev/tty8
/dev/tty11  /dev/tty22  /dev/tty33  /dev/tty44  /dev/tty55  /dev/tty9
/dev/tty12  /dev/tty23  /dev/tty34  /dev/tty45  /dev/tty56  /dev/ttyACM0
/dev/tty13  /dev/tty24  /dev/tty35  /dev/tty46  /dev/tty57  /dev/ttyAMA0
/dev/tty14  /dev/tty25  /dev/tty36  /dev/tty47  /dev/tty58  /dev/ttyprintk
/dev/tty15  /dev/tty26  /dev/tty37  /dev/tty48  /dev/tty59
/dev/tty16  /dev/tty27  /dev/tty38  /dev/tty49  /dev/tty6
/dev/tty17  /dev/tty28  /dev/tty39  /dev/tty5   /dev/tty60
/dev/tty18  /dev/tty29  /dev/tty4   /dev/tty50  /dev/tty61
pi@raspberrypi ~> ls /dev/tty*
30m/dev/tty    /dev/tty19  /dev/tty3   /dev/tty40  /dev/tty51  /dev/tty62
/dev/tty0   /dev/tty2   /dev/tty30  /dev/tty41  /dev/tty52  /dev/tty63
/dev/tty1   /dev/tty20  /dev/tty31  /dev/tty42  /dev/tty53  /dev/tty7
/dev/tty10  /dev/tty21  /dev/tty32  /dev/tty43  /dev/tty54  /dev/tty8
/dev/tty11  /dev/tty22  /dev/tty33  /dev/tty44  /dev/tty55  /dev/tty9
/dev/tty12  /dev/tty23  /dev/tty34  /dev/tty45  /dev/tty56  /dev/ttyACM0
/dev/tty13  /dev/tty24  /dev/tty35  /dev/tty46  /dev/tty57  /dev/ttyAMA0
/dev/tty14  /dev/tty25  /dev/tty36  /dev/tty47  /dev/tty58  /dev/ttyprintk
/dev/tty15  /dev/tty26  /dev/tty37  /dev/tty48  /dev/tty59
/dev/tty16  /dev/tty27  /dev/tty38  /dev/tty49  /dev/tty6
/dev/tty17  /dev/tty28  /dev/tty39  /dev/tty5   /dev/tty60
/dev/tty18  /dev/tty29  /dev/tty4   /dev/tty50  /dev/tty61
pi@raspberrypi ~> cd ~/Desktop/serial-web-terminal/
pi@raspberrypi ~/D/serial-web-terminal> ls
30mbitty.js               index.js*  npm-debug.log  README.md
bitty-screen-shot.png  LICENSE    package.json
pi@raspberrypi ~/D/serial-web-terminal> npm install
npm http GET http://registry.npmjs.org/tty.js
npm http GET http://registry.npmjs.org/shelljs
npm http GET http://registry.npmjs.org/optimist
npm http GET http://registry.npmjs.org/serialport
npm http 304 http://registry.npmjs.org/serialport
npm http 200 http://registry.npmjs.org/optimist
npm http 200 http://registry.npmjs.org/shelljs

npm ERR! Error: No compatible version found: serialport@'>=1.1.0'
npm ERR! Valid install targets:
npm ERR! ["0.1.0","0.1.1","0.1.3","0.2.0","0.2.2","0.2.3","0.2.4","0.2.5","0.2.6","0.2.7","0.2.8","0.2.9","0.3.0","0.6.0","0.6.1","0.6.2","0.6.3","0.6.5","0.6.6","0.6.7","0.7.0","0.7.1","0.7.2","0.7.3","0.7.4","0.7.5","1.0.0","1.0.1","1.0.2","1.0.3","1.0.4","1.0.5","1.0.6","1.0.7"]
npm ERR!     at installTargetsError (/usr/share/npm/lib/cache.js:488:10)
npm ERR!     at next_ (/usr/share/npm/lib/cache.js:438:17)
npm ERR!     at next (/usr/share/npm/lib/cache.js:415:44)
npm ERR!     at /usr/share/npm/lib/cache.js:408:5
npm ERR!     at saved (/usr/share/npm/lib/utils/npm-registry-client/get.js:147:7)
npm ERR!     at Object.oncomplete (/usr/lib/nodejs/graceful-fs.js:230:7)
npm ERR! You may report this log at:
npm ERR!     <http://bugs.debian.org/npm>
npm ERR! or use
npm ERR!     reportbug --attach /home/pi/Desktop/serial-web-terminal/npm-debug.log npm
npm ERR!
npm ERR! System Linux 3.10.36+
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! cwd /home/pi/Desktop/serial-web-terminal
npm ERR! node -v v0.6.19
npm ERR! npm -v 1.1.4
npm ERR! message No compatible version found: serialport@'>=1.1.0'
npm ERR! message Valid install targets:
npm ERR! message ["0.1.0","0.1.1","0.1.3","0.2.0","0.2.2","0.2.3","0.2.4","0.2.5","0.2.6","0.2.7","0.2.8","0.2.9","0.3.0","0.6.0","0.6.1","0.6.2","0.6.3","0.6.5","0.6.6","0.6.7","0.7.0","0.7.1","0.7.2","0.7.3","0.7.4","0.7.5","1.0.0","1.0.1","1.0.2","1.0.3","1.0.4","1.0.5","1.0.6","1.0.7"]

npm ERR! Error: EACCES, open 'npm-debug.log'
npm ERR!
npm ERR! Please try running this command again as root/Administrator.
npm ERR!
npm ERR! System Linux 3.10.36+
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! cwd /home/pi/Desktop/serial-web-terminal
npm ERR! node -v v0.6.19
npm ERR! npm -v 1.1.4
npm ERR! path npm-debug.log
npm ERR! code EACCES
npm ERR! message EACCES, open 'npm-debug.log'
npm ERR! errno {}
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /home/pi/Desktop/serial-web-terminal/npm-debug.log
npm not ok
pi@raspberrypi ~/D/serial-web-terminal> nodejs index.js

module.js:337
    throw new Error("Cannot find module '" + request + "'");
          ^
Error: Cannot find module 'optimist'
    at Function._resolveFilename (module.js:337:11)
    at Function._load (module.js:279:25)
    at Module.require (module.js:359:17)
    at require (module.js:375:17)
    at Object.<anonymous> (/home/pi/Desktop/serial-web-terminal/index.js:6:11)
    at Module._compile (module.js:446:26)
    at Object..js (module.js:464:10)
    at Module.load (module.js:353:32)
    at Function._load (module.js:311:12)
    at Array.0 (module.js:484:10)
pi@raspberrypi ~/D/serial-web-terminal> sudo apt-get install nodejs-legacy
Reading package lists... Done
Building dependency tree
0m
Reading state information... Done
The following packages were automatically installed and are no longer required:
  ax25-node libax25 openbsd-inetd
Use 'apt-get autoremove' to remove them.
The following packages will be REMOVED:
  node
The following NEW packages will be installed:
  nodejs-legacy
0 upgraded, 1 newly installed, 1 to remove and 1 not upgraded.
Need to get 52.0 kB of archives.
After this operation, 69.6 kB of additional disk space will be used.
Do you want to continue [Y/n]? y
Get:1 http://mirrordirector.raspbian.org/raspbian/ wheezy/main nodejs-legacy all 0.6.19~dfsg1-6 [52.0 kB]
Fetched 52.0 kB in 0s (67.6 kB/s)
(Reading database ... 73087 files and directories currently installed.)
Removing node ...
Processing triggers for man-db ...
Selecting previously unselected package nodejs-legacy.
(Reading database ... 73082 files and directories currently installed.)
Unpacking nodejs-legacy (from .../nodejs-legacy_0.6.19~dfsg1-6_all.deb) ...
Processing triggers for man-db ...
Setting up nodejs-legacy (0.6.19~dfsg1-6) ...
pi@raspberrypi ~/D/serial-web-terminal> htop
pi@raspberrypi ~/D/serial-web-terminal> node --version
v0.6.19
pi@raspberrypi ~/D/serial-web-terminal> nodejs --version
v0.6.19
pi@raspberrypi ~/D/serial-web-terminal> node index.ks

module.js:337
    throw new Error("Cannot find module '" + request + "'");
          ^
Error: Cannot find module '/home/pi/Desktop/serial-web-terminal/index.ks'
    at Function._resolveFilename (module.js:337:11)
    at Function._load (module.js:279:25)
    at Array.0 (module.js:484:10)
    at EventEmitter._tickCallback (node.js:190:39)
pi@raspberrypi ~/D/serial-web-terminal> node index.js

module.js:337
    throw new Error("Cannot find module '" + request + "'");
          ^
Error: Cannot find module 'optimist'
    at Function._resolveFilename (module.js:337:11)
    at Function._load (module.js:279:25)
    at Module.require (module.js:359:17)
    at require (module.js:375:17)
    at Object.<anonymous> (/home/pi/Desktop/serial-web-terminal/index.js:6:11)
    at Module._compile (module.js:446:26)
    at Object..js (module.js:464:10)
    at Module.load (module.js:353:32)
    at Function._load (module.js:311:12)
    at Array.0 (module.js:484:10)
pi@raspberrypi ~/D/serial-web-terminal> npm install
0mnpm http GET http://registry.npmjs.org/tty.js
npm http GET http://registry.npmjs.org/shelljs
npm http GET http://registry.npmjs.org/optimist
npm http GET http://registry.npmjs.org/serialport
npm http 304 http://registry.npmjs.org/serialport

npm ERR! Error: No compatible version found: serialport@'>=1.1.0'
npm ERR! Valid install targets:
npm ERR! ["0.1.0","0.1.1","0.1.3","0.2.0","0.2.2","0.2.3","0.2.4","0.2.5","0.2.6","0.2.7","0.2.8","0.2.9","0.3.0","0.6.0","0.6.1","0.6.2","0.6.3","0.6.5","0.6.6","0.6.7","0.7.0","0.7.1","0.7.2","0.7.3","0.7.4","0.7.5","1.0.0","1.0.1","1.0.2","1.0.3","1.0.4","1.0.5","1.0.6","1.0.7"]
npm ERR!     at installTargetsError (/usr/share/npm/lib/cache.js:488:10)
npm ERR!     at next_ (/usr/share/npm/lib/cache.js:438:17)
npm ERR!     at next (/usr/share/npm/lib/cache.js:415:44)
npm ERR!     at /usr/share/npm/lib/cache.js:408:5
npm ERR!     at saved (/usr/share/npm/lib/utils/npm-registry-client/get.js:147:7)
npm ERR!     at Object.oncomplete (/usr/lib/nodejs/graceful-fs.js:230:7)
npm ERR! You may report this log at:
npm ERR!     <http://bugs.debian.org/npm>
npm ERR! or use
npm ERR!     reportbug --attach /home/pi/Desktop/serial-web-terminal/npm-debug.log npm
npm ERR!
npm ERR! System Linux 3.10.36+
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! cwd /home/pi/Desktop/serial-web-terminal
npm ERR! node -v v0.6.19
npm ERR! npm -v 1.1.4
npm ERR! message No compatible version found: serialport@'>=1.1.0'
npm ERR! message Valid install targets:
npm ERR! message ["0.1.0","0.1.1","0.1.3","0.2.0","0.2.2","0.2.3","0.2.4","0.2.5","0.2.6","0.2.7","0.2.8","0.2.9","0.3.0","0.6.0","0.6.1","0.6.2","0.6.3","0.6.5","0.6.6","0.6.7","0.7.0","0.7.1","0.7.2","0.7.3","0.7.4","0.7.5","1.0.0","1.0.1","1.0.2","1.0.3","1.0.4","1.0.5","1.0.6","1.0.7"]

npm ERR! Error: EACCES, open 'npm-debug.log'
npm ERR!
npm ERR! Please try running this command again as root/Administrator.
npm ERR!
npm ERR! System Linux 3.10.36+
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! cwd /home/pi/Desktop/serial-web-terminal
npm ERR! node -v v0.6.19
npm ERR! npm -v 1.1.4
npm ERR! path npm-debug.log
npm ERR! code EACCES
npm ERR! message EACCES, open 'npm-debug.log'
npm ERR! errno {}
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /home/pi/Desktop/serial-web-terminal/npm-debug.log
npm not ok
pi@raspberrypi ~/D/serial-web-terminal> sudo npm install
npm http GET https://registry.npmjs.org/serialport
npm http GET https://registry.npmjs.org/tty.js
npm http GET https://registry.npmjs.org/shelljs
npm http GET https://registry.npmjs.org/optimist

npm ERR! Error: failed to fetch from registry: shelljs
npm ERR!     at /usr/share/npm/lib/utils/npm-registry-client/get.js:139:12
npm ERR!     at cb (/usr/share/npm/lib/utils/npm-registry-client/request.js:31:9)
npm ERR!     at Request._callback (/usr/share/npm/lib/utils/npm-registry-client/request.js:136:18)
npm ERR!     at Request.callback (/usr/lib/nodejs/request/main.js:119:22)
npm ERR!     at Request.<anonymous> (/usr/lib/nodejs/request/main.js:212:58)
npm ERR!     at Request.emit (events.js:88:20)
npm ERR!     at ClientRequest.<anonymous> (/usr/lib/nodejs/request/main.js:412:12)
npm ERR!     at ClientRequest.g (events.js:156:14)
npm ERR!     at ClientRequest.emit (events.js:67:17)
npm ERR!     at HTTPParser.parserOnIncomingClient [as onIncoming] (http.js:1256:7)
npm ERR! You may report this log at:
npm ERR!     <http://bugs.debian.org/npm>
npm ERR! or use
npm ERR!     reportbug --attach /home/pi/Desktop/serial-web-terminal/npm-debug.log npm
npm ERR!
npm ERR! System Linux 3.10.36+
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! cwd /home/pi/Desktop/serial-web-terminal
npm ERR! node -v v0.6.19
npm ERR! npm -v 1.1.4
npm ERR! message failed to fetch from registry: shelljs
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /home/pi/Desktop/serial-web-terminal/npm-debug.log
npm not ok
pi@raspberrypi ~/D/serial-web-terminal>
```

**Comment by billroy** [comment]
Sorry you are having problems.  Let’s see if we can get you sorted out.

Your version of node.js and npm are very old.  You will need to upgrade to node v0.10.x before the npm install step will do anything but complain.  Install a new version of node, delete the node_modules directory inside the serial_web_terminal directory, and try npm-install again.

When I plug my Arduino into my RasPi, I get a device named /dev/ttyUSB0.  I don’t see that in your listing.  You’ll need that working, too; I don’t know what the latest guidance about FTDI drivers is for your version of Pi linux, but you might be sure you’ve installed drivers for the usbserial port if they are needed.  The Arduino site will have documentation for this if the Pi world doesn’t.

Try those and see how far it gets you.

-br

**Comment by sdaitzman** [comment]
The old version of node was because the new version didn't work, but I'll try the new version again... should I apt-get install the node or nodejs package?

My Arduino shows up as /dev/ttyACM0, and ls /dev/ttyUSB\* returns nothing. I tried installing the FTDI drivers from source successfully but the Arduino still lives at /dev/ttyACM0. Is there a better way?

**Comment by billroy** [comment]
The newer version of Node is going to be required.  I’m not sure which apt-get package that lives in…

If you have the FTDI drivers installed and working at /dev/ttyACM0, you can start the serial web terminal using the -p argument to specify that port:

```
node index.js -p /dev/ttyACM0
```

Have you tested the drivers in some way, perhaps by uploading an Arduino program?

-br

**Comment by sdaitzman** [comment]
Will node v0.10.2 and npm v1.2.15 be new enough?

**Comment by billroy** [comment]
Those are new enough to definitely be worth a try.

-br

**Comment by sdaitzman** [comment]
Success :smile:

I used instructions from http://joshondesign.com/2013/10/23/noderpi to install node, and everything else worked exactly as you said!
